- include: config_sys.yml
  when: clickhouse_rt_is_installed.rc == 0 and clickhouse_remove|bool == False
  tags: [config,config_sys]

- include: config_db.yml
  when: clickhouse_rt_is_installed.rc == 0 and clickhouse_remove|bool == False
  tags: [config,config_db]
